server:
  port: 9090

spring:
  application:
    name: Community Gateway Service
  cloud:
    gateway:
      routes:
        - id: posts-route
          uri: http://localhost:8081
          predicates:
            - Path=/post
          filters:
            - PrefixPath=/api

        - id: comments-route
          uri: http://localhost:8082
          predicates:
            - Path=/comments
          filters:
            - PrefixPath=/api

        - id: community-route
          uri: http://localhost:8084
          predicates:
            - Path=/community
          filters:
            - PrefixPath=/api

        - id: groups-route
          uri: http://localhost:8084
          predicates:
            - Path=/groups
          filters:
            - PrefixPath=/api

        - id: aggregator-routes
          uri: http://localhost:8083
          predicates:
            - Path=/group/**
#            - Path=/community/**
          filters:
            - PrefixPath=/my-community