server:
  port: 9191

#resilience4j:
#  circuitbreaker:
#    instances:
#      myCircuitBreaker:
#        registerHealthIndicator: true
#        failureRateThreshold: 50
#        waitDurationInOpenState: 5s
#        permittedNumberOfCallsInHalfOpenState: 3
#        slidingWindowType: COUNT_BASED
#        slidingWindowSize: 10
#  retryInstances:
#    instances:
#      myCircuitBreaker:
#        maxAttempts: 3
#        waitDuration: 500ms

management:
  tracing:
    sampling:
      probability: 1.0

spring:
  application:
    name: Community Gateway Service
  cloud:
#    circuitbreaker:
#      resilience4j:
#        enabled: true
    gateway:
      routes:
        - id: posts-route
          uri: http://localhost:8081
          predicates:
            - Path=/post
          filters:
            - PrefixPath=/api

        - id: comments-route
          uri: http://localhost:8082
          predicates:
            - Path=/comments/**
          filters:
            - PrefixPath=/api
            - name: CircuitBreaker
              args:
                name: myCircuitBreaker
                fallbackUri: forward:/fallback/commentService
        - id: community-route
          uri: http://localhost:8084
          predicates:
            - Path=/community
          filters:
            - PrefixPath=/api

        - id: groups-route
          uri: http://localhost:8084
          predicates:
            - Path=/groups
          filters:
            - PrefixPath=/api

        - id: aggregator-routes
          uri: http://localhost:8083
          predicates:
            - Path=/group/**
#            - Path=/community/**
          filters:
            - PrefixPath=/my-community
  security:
    oAuth2:
      resourceServer:
        jwt:
          issuer-uri: http://localhost:9090/realms/community-services-realm